twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_3_layout.html.twig' ]
    globals:
        report_email: '%env(REPORT_EMAIL)%'
        app_name: '%env(APP_NAME)%'


when@test:
    twig:
        strict_variables: true
